# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qfvgwindow.ui'
#
# Created: Tue Jul 10 01:11:41 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1154, 766)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 10, 1101, 711))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.framesTimelineListView = QtGui.QListView(self.tab_3)
        self.framesTimelineListView.setGeometry(QtCore.QRect(10, 80, 1051, 211))
        self.framesTimelineListView.setFlow(QtGui.QListView.LeftToRight)
        self.framesTimelineListView.setResizeMode(QtGui.QListView.Adjust)
        self.framesTimelineListView.setObjectName(_fromUtf8("framesTimelineListView"))
        self.label_15 = QtGui.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(10, 330, 101, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.framesCountLabel = QtGui.QLabel(self.tab_3)
        self.framesCountLabel.setGeometry(QtCore.QRect(100, 330, 62, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.framesCountLabel.setFont(font)
        self.framesCountLabel.setObjectName(_fromUtf8("framesCountLabel"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.frame2GraphicsView = QtGui.QGraphicsView(self.tab)
        self.frame2GraphicsView.setGeometry(QtCore.QRect(290, 30, 256, 192))
        self.frame2GraphicsView.setDragMode(QtGui.QGraphicsView.ScrollHandDrag)
        self.frame2GraphicsView.setObjectName(_fromUtf8("frame2GraphicsView"))
        self.frame2ReconstructedGraphicsView = QtGui.QGraphicsView(self.tab)
        self.frame2ReconstructedGraphicsView.setGeometry(QtCore.QRect(840, 30, 256, 192))
        self.frame2ReconstructedGraphicsView.setDragMode(QtGui.QGraphicsView.ScrollHandDrag)
        self.frame2ReconstructedGraphicsView.setObjectName(_fromUtf8("frame2ReconstructedGraphicsView"))
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(399, 220, 151, 32))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_8.addWidget(self.label_13)
        self.zoomInPushButton = QtGui.QPushButton(self.layoutWidget)
        self.zoomInPushButton.setObjectName(_fromUtf8("zoomInPushButton"))
        self.horizontalLayout_8.addWidget(self.zoomInPushButton)
        self.zoomOutPushButton = QtGui.QPushButton(self.layoutWidget)
        self.zoomOutPushButton.setObjectName(_fromUtf8("zoomOutPushButton"))
        self.horizontalLayout_8.addWidget(self.zoomOutPushButton)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(560, 10, 161, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(840, 10, 161, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 10, 131, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.frame1GraphicsView = QtGui.QGraphicsView(self.tab)
        self.frame1GraphicsView.setGeometry(QtCore.QRect(20, 31, 256, 192))
        self.frame1GraphicsView.setDragMode(QtGui.QGraphicsView.ScrollHandDrag)
        self.frame1GraphicsView.setObjectName(_fromUtf8("frame1GraphicsView"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(290, 10, 121, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(560, 250, 531, 321))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_2.addWidget(self.label_17)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.MADThresholdSpingBox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.MADThresholdSpingBox.setDecimals(6)
        self.MADThresholdSpingBox.setSingleStep(0.001)
        self.MADThresholdSpingBox.setProperty("value", 0.02)
        self.MADThresholdSpingBox.setObjectName(_fromUtf8("MADThresholdSpingBox"))
        self.horizontalLayout.addWidget(self.MADThresholdSpingBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.reconstructFrame2PushButton = QtGui.QPushButton(self.groupBox_2)
        self.reconstructFrame2PushButton.setObjectName(_fromUtf8("reconstructFrame2PushButton"))
        self.horizontalLayout_5.addWidget(self.reconstructFrame2PushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_2.addWidget(self.label_16)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_10)
        self.zeroVectorsPercentLabel = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.zeroVectorsPercentLabel.setFont(font)
        self.zeroVectorsPercentLabel.setObjectName(_fromUtf8("zeroVectorsPercentLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.zeroVectorsPercentLabel)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_11)
        self.movedVectorsPercentLabel = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.movedVectorsPercentLabel.setFont(font)
        self.movedVectorsPercentLabel.setObjectName(_fromUtf8("movedVectorsPercentLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.movedVectorsPercentLabel)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_8)
        self.newBlocksPercentLabel = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.newBlocksPercentLabel.setFont(font)
        self.newBlocksPercentLabel.setObjectName(_fromUtf8("newBlocksPercentLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.newBlocksPercentLabel)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_9)
        self.compressionRatioLabel = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(False)
        font.setWeight(50)
        self.compressionRatioLabel.setFont(font)
        self.compressionRatioLabel.setObjectName(_fromUtf8("compressionRatioLabel"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.compressionRatioLabel)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.searchElapsedTimeLabel = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.searchElapsedTimeLabel.setFont(font)
        self.searchElapsedTimeLabel.setObjectName(_fromUtf8("searchElapsedTimeLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.searchElapsedTimeLabel)
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_14)
        self.MADsCheckedLabel = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.MADsCheckedLabel.setFont(font)
        self.MADsCheckedLabel.setObjectName(_fromUtf8("MADsCheckedLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.MADsCheckedLabel)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.frame2CompressedGraphicsView = QtGui.QGraphicsView(self.tab)
        self.frame2CompressedGraphicsView.setGeometry(QtCore.QRect(560, 30, 256, 192))
        self.frame2CompressedGraphicsView.setDragMode(QtGui.QGraphicsView.ScrollHandDrag)
        self.frame2CompressedGraphicsView.setObjectName(_fromUtf8("frame2CompressedGraphicsView"))
        self.chooseFrame2PushButton = QtGui.QPushButton(self.tab)
        self.chooseFrame2PushButton.setGeometry(QtCore.QRect(450, 0, 91, 32))
        self.chooseFrame2PushButton.setObjectName(_fromUtf8("chooseFrame2PushButton"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(20, 250, 521, 221))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_3.addWidget(self.label_7)
        self.blockSizeSpinBox = QtGui.QSpinBox(self.groupBox)
        self.blockSizeSpinBox.setProperty("value", 16)
        self.blockSizeSpinBox.setObjectName(_fromUtf8("blockSizeSpinBox"))
        self.horizontalLayout_3.addWidget(self.blockSizeSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_7.addWidget(self.label_12)
        self.searchTypeComboBox = QtGui.QComboBox(self.groupBox)
        self.searchTypeComboBox.setObjectName(_fromUtf8("searchTypeComboBox"))
        self.searchTypeComboBox.addItem(_fromUtf8(""))
        self.searchTypeComboBox.addItem(_fromUtf8(""))
        self.searchTypeComboBox.addItem(_fromUtf8(""))
        self.searchTypeComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.searchTypeComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.searchWindowSizeLabel = QtGui.QLabel(self.groupBox)
        self.searchWindowSizeLabel.setObjectName(_fromUtf8("searchWindowSizeLabel"))
        self.horizontalLayout_2.addWidget(self.searchWindowSizeLabel)
        self.searchWindowSizeSpinBox = QtGui.QSpinBox(self.groupBox)
        self.searchWindowSizeSpinBox.setMaximum(100)
        self.searchWindowSizeSpinBox.setProperty("value", 7)
        self.searchWindowSizeSpinBox.setObjectName(_fromUtf8("searchWindowSizeSpinBox"))
        self.horizontalLayout_2.addWidget(self.searchWindowSizeSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.searchStepLabel = QtGui.QLabel(self.groupBox)
        self.searchStepLabel.setObjectName(_fromUtf8("searchStepLabel"))
        self.horizontalLayout_6.addWidget(self.searchStepLabel)
        self.searchStepSpinBox = QtGui.QSpinBox(self.groupBox)
        self.searchStepSpinBox.setMaximum(100)
        self.searchStepSpinBox.setProperty("value", 6)
        self.searchStepSpinBox.setObjectName(_fromUtf8("searchStepSpinBox"))
        self.horizontalLayout_6.addWidget(self.searchStepSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.findVectorsPushButton = QtGui.QPushButton(self.groupBox)
        self.findVectorsPushButton.setObjectName(_fromUtf8("findVectorsPushButton"))
        self.horizontalLayout_4.addWidget(self.findVectorsPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.showLuminanceCheckBox = QtGui.QCheckBox(self.tab)
        self.showLuminanceCheckBox.setGeometry(QtCore.QRect(20, 230, 171, 20))
        self.showLuminanceCheckBox.setObjectName(_fromUtf8("showLuminanceCheckBox"))
        self.chooseFrame1PushButton = QtGui.QPushButton(self.tab)
        self.chooseFrame1PushButton.setGeometry(QtCore.QRect(190, 0, 91, 32))
        self.chooseFrame1PushButton.setObjectName(_fromUtf8("chooseFrame1PushButton"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.framesTimelineListView2 = QtGui.QListView(self.tab_2)
        self.framesTimelineListView2.setGeometry(QtCore.QRect(10, 30, 1071, 181))
        self.framesTimelineListView2.setFlow(QtGui.QListView.LeftToRight)
        self.framesTimelineListView2.setObjectName(_fromUtf8("framesTimelineListView2"))
        self.label_18 = QtGui.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(10, 10, 141, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(10, 260, 191, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.analyzedFramesTimelineListView = QtGui.QListView(self.tab_2)
        self.analyzedFramesTimelineListView.setGeometry(QtCore.QRect(10, 280, 1071, 161))
        self.analyzedFramesTimelineListView.setFlow(QtGui.QListView.LeftToRight)
        self.analyzedFramesTimelineListView.setObjectName(_fromUtf8("analyzedFramesTimelineListView"))
        self.label_20 = QtGui.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(10, 230, 231, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.maxVectDistThreSpinBox = QtGui.QDoubleSpinBox(self.tab_2)
        self.maxVectDistThreSpinBox.setGeometry(QtCore.QRect(250, 220, 101, 31))
        self.maxVectDistThreSpinBox.setSingleStep(0.2)
        self.maxVectDistThreSpinBox.setProperty("value", 5.0)
        self.maxVectDistThreSpinBox.setObjectName(_fromUtf8("maxVectDistThreSpinBox"))
        self.interpolatedFramesTimelineListView = QtGui.QListView(self.tab_2)
        self.interpolatedFramesTimelineListView.setGeometry(QtCore.QRect(10, 480, 1071, 201))
        self.interpolatedFramesTimelineListView.setFlow(QtGui.QListView.LeftToRight)
        self.interpolatedFramesTimelineListView.setObjectName(_fromUtf8("interpolatedFramesTimelineListView"))
        self.label_21 = QtGui.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(10, 450, 191, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.analyzeVideoPushButton = QtGui.QPushButton(self.tab_2)
        self.analyzeVideoPushButton.setGeometry(QtCore.QRect(360, 220, 114, 32))
        self.analyzeVideoPushButton.setObjectName(_fromUtf8("analyzeVideoPushButton"))
        self.interpolateVideoPushButton = QtGui.QPushButton(self.tab_2)
        self.interpolateVideoPushButton.setGeometry(QtCore.QRect(800, 450, 114, 32))
        self.interpolateVideoPushButton.setObjectName(_fromUtf8("interpolateVideoPushButton"))
        self.saveVideoPushButton = QtGui.QPushButton(self.tab_2)
        self.saveVideoPushButton.setGeometry(QtCore.QRect(920, 450, 161, 32))
        self.saveVideoPushButton.setObjectName(_fromUtf8("saveVideoPushButton"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1154, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuOpen_video = QtGui.QMenu(self.menubar)
        self.menuOpen_video.setObjectName(_fromUtf8("menuOpen_video"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_video = QtGui.QAction(MainWindow)
        self.actionOpen_video.setObjectName(_fromUtf8("actionOpen_video"))
        self.menuOpen_video.addAction(self.actionOpen_video)
        self.menubar.addAction(self.menuOpen_video.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "# of frames:", None, QtGui.QApplication.UnicodeUTF8))
        self.framesCountLabel.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Frames viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomInPushButton.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomOutPushButton.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Frame #2 compressed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Frame #2 reconstructed", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Original frame #1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Original frame #2", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Frame reconstruction", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "MAD Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.reconstructFrame2PushButton.setText(QtGui.QApplication.translate("MainWindow", "Reconstruct  frame #2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "% of zero vectors:", None, QtGui.QApplication.UnicodeUTF8))
        self.zeroVectorsPercentLabel.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "% of motion vectors:", None, QtGui.QApplication.UnicodeUTF8))
        self.movedVectorsPercentLabel.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "% of new blocks:", None, QtGui.QApplication.UnicodeUTF8))
        self.newBlocksPercentLabel.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Compresssion ratio:", None, QtGui.QApplication.UnicodeUTF8))
        self.compressionRatioLabel.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Search time elapsed:", None, QtGui.QApplication.UnicodeUTF8))
        self.searchElapsedTimeLabel.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "MADs checked:", None, QtGui.QApplication.UnicodeUTF8))
        self.MADsCheckedLabel.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.chooseFrame2PushButton.setText(QtGui.QApplication.translate("MainWindow", "Choose...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Motion vectors", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Block size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Search algorithm", None, QtGui.QApplication.UnicodeUTF8))
        self.searchTypeComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Full", None, QtGui.QApplication.UnicodeUTF8))
        self.searchTypeComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Q-Step", None, QtGui.QApplication.UnicodeUTF8))
        self.searchTypeComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "2D Logarithmic", None, QtGui.QApplication.UnicodeUTF8))
        self.searchTypeComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "Orthogonal", None, QtGui.QApplication.UnicodeUTF8))
        self.searchWindowSizeLabel.setText(QtGui.QApplication.translate("MainWindow", "Search window size", None, QtGui.QApplication.UnicodeUTF8))
        self.searchStepLabel.setText(QtGui.QApplication.translate("MainWindow", "Step", None, QtGui.QApplication.UnicodeUTF8))
        self.findVectorsPushButton.setText(QtGui.QApplication.translate("MainWindow", "Find vectors", None, QtGui.QApplication.UnicodeUTF8))
        self.showLuminanceCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Show only luminance", None, QtGui.QApplication.UnicodeUTF8))
        self.chooseFrame1PushButton.setText(QtGui.QApplication.translate("MainWindow", "Choose...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Frame analyzer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Original video frames", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Analyzed video frames", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Maximum motion vector distance:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Interpolated video frames", None, QtGui.QApplication.UnicodeUTF8))
        self.analyzeVideoPushButton.setText(QtGui.QApplication.translate("MainWindow", "Analyze", None, QtGui.QApplication.UnicodeUTF8))
        self.interpolateVideoPushButton.setText(QtGui.QApplication.translate("MainWindow", "Interpolate", None, QtGui.QApplication.UnicodeUTF8))
        self.saveVideoPushButton.setText(QtGui.QApplication.translate("MainWindow", "Save video to disk", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Video analyzer", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOpen_video.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_video.setText(QtGui.QApplication.translate("MainWindow", "Open video...", None, QtGui.QApplication.UnicodeUTF8))

