# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/qfvgwindow.ui'
#
# Created: Wed May 30 12:08:22 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1139, 633)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 131, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 30, 121, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.frame1GraphicsView = QtGui.QGraphicsView(self.centralwidget)
        self.frame1GraphicsView.setGeometry(QtCore.QRect(20, 51, 256, 191))
        self.frame1GraphicsView.setObjectName(_fromUtf8("frame1GraphicsView"))
        self.frame2GraphicsView = QtGui.QGraphicsView(self.centralwidget)
        self.frame2GraphicsView.setGeometry(QtCore.QRect(290, 50, 256, 192))
        self.frame2GraphicsView.setObjectName(_fromUtf8("frame2GraphicsView"))
        self.chooseFrame1PushButton = QtGui.QPushButton(self.centralwidget)
        self.chooseFrame1PushButton.setGeometry(QtCore.QRect(190, 20, 91, 32))
        self.chooseFrame1PushButton.setObjectName(_fromUtf8("chooseFrame1PushButton"))
        self.chooseFrame2PushButton = QtGui.QPushButton(self.centralwidget)
        self.chooseFrame2PushButton.setGeometry(QtCore.QRect(450, 20, 91, 32))
        self.chooseFrame2PushButton.setObjectName(_fromUtf8("chooseFrame2PushButton"))
        self.showLuminanceCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.showLuminanceCheckBox.setGeometry(QtCore.QRect(20, 250, 171, 20))
        self.showLuminanceCheckBox.setObjectName(_fromUtf8("showLuminanceCheckBox"))
        self.frame2CompressedGraphicsView = QtGui.QGraphicsView(self.centralwidget)
        self.frame2CompressedGraphicsView.setGeometry(QtCore.QRect(560, 50, 256, 192))
        self.frame2CompressedGraphicsView.setObjectName(_fromUtf8("frame2CompressedGraphicsView"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(560, 30, 161, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.frame2ReconstructedGraphicsView = QtGui.QGraphicsView(self.centralwidget)
        self.frame2ReconstructedGraphicsView.setGeometry(QtCore.QRect(840, 50, 256, 192))
        self.frame2ReconstructedGraphicsView.setObjectName(_fromUtf8("frame2ReconstructedGraphicsView"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(840, 30, 161, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 270, 521, 221))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_3.addWidget(self.label_7)
        self.blockSizeSpinBox = QtGui.QSpinBox(self.groupBox)
        self.blockSizeSpinBox.setProperty("value", 8)
        self.blockSizeSpinBox.setObjectName(_fromUtf8("blockSizeSpinBox"))
        self.horizontalLayout_3.addWidget(self.blockSizeSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_7.addWidget(self.label_12)
        self.searchTypeComboBox = QtGui.QComboBox(self.groupBox)
        self.searchTypeComboBox.setObjectName(_fromUtf8("searchTypeComboBox"))
        self.searchTypeComboBox.addItem(_fromUtf8(""))
        self.searchTypeComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.searchTypeComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.searchWindowSizeLabel = QtGui.QLabel(self.groupBox)
        self.searchWindowSizeLabel.setObjectName(_fromUtf8("searchWindowSizeLabel"))
        self.horizontalLayout_2.addWidget(self.searchWindowSizeLabel)
        self.searchWindowSizeSpinBox = QtGui.QSpinBox(self.groupBox)
        self.searchWindowSizeSpinBox.setMaximum(100)
        self.searchWindowSizeSpinBox.setProperty("value", 7)
        self.searchWindowSizeSpinBox.setObjectName(_fromUtf8("searchWindowSizeSpinBox"))
        self.horizontalLayout_2.addWidget(self.searchWindowSizeSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.searchStepLabel = QtGui.QLabel(self.groupBox)
        self.searchStepLabel.setObjectName(_fromUtf8("searchStepLabel"))
        self.horizontalLayout_6.addWidget(self.searchStepLabel)
        self.searchStepSpinBox = QtGui.QSpinBox(self.groupBox)
        self.searchStepSpinBox.setMaximum(100)
        self.searchStepSpinBox.setProperty("value", 6)
        self.searchStepSpinBox.setObjectName(_fromUtf8("searchStepSpinBox"))
        self.horizontalLayout_6.addWidget(self.searchStepSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.findVectorsPushButton = QtGui.QPushButton(self.groupBox)
        self.findVectorsPushButton.setObjectName(_fromUtf8("findVectorsPushButton"))
        self.horizontalLayout_4.addWidget(self.findVectorsPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(560, 270, 531, 311))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_2.addWidget(self.label_17)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.MADThresholdSpingBox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.MADThresholdSpingBox.setDecimals(3)
        self.MADThresholdSpingBox.setSingleStep(0.001)
        self.MADThresholdSpingBox.setProperty("value", 0.02)
        self.MADThresholdSpingBox.setObjectName(_fromUtf8("MADThresholdSpingBox"))
        self.horizontalLayout.addWidget(self.MADThresholdSpingBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.reconstructFrame2PushButton = QtGui.QPushButton(self.groupBox_2)
        self.reconstructFrame2PushButton.setObjectName(_fromUtf8("reconstructFrame2PushButton"))
        self.horizontalLayout_5.addWidget(self.reconstructFrame2PushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_2.addWidget(self.label_16)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_10)
        self.zeroVectorsPercentLabel = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.zeroVectorsPercentLabel.setFont(font)
        self.zeroVectorsPercentLabel.setObjectName(_fromUtf8("zeroVectorsPercentLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.zeroVectorsPercentLabel)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_11)
        self.movedVectorsPercentLabel = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.movedVectorsPercentLabel.setFont(font)
        self.movedVectorsPercentLabel.setObjectName(_fromUtf8("movedVectorsPercentLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.movedVectorsPercentLabel)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_8)
        self.newBlocksPercentLabel = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.newBlocksPercentLabel.setFont(font)
        self.newBlocksPercentLabel.setObjectName(_fromUtf8("newBlocksPercentLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.newBlocksPercentLabel)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_9)
        self.compressionRatioLabel = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(False)
        font.setWeight(50)
        self.compressionRatioLabel.setFont(font)
        self.compressionRatioLabel.setObjectName(_fromUtf8("compressionRatioLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.compressionRatioLabel)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.searchElapsedTimeLabel = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.searchElapsedTimeLabel.setFont(font)
        self.searchElapsedTimeLabel.setObjectName(_fromUtf8("searchElapsedTimeLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.searchElapsedTimeLabel)
        self.verticalLayout_2.addLayout(self.formLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1139, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Original frame #1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Original frame #2", None, QtGui.QApplication.UnicodeUTF8))
        self.chooseFrame1PushButton.setText(QtGui.QApplication.translate("MainWindow", "Choose...", None, QtGui.QApplication.UnicodeUTF8))
        self.chooseFrame2PushButton.setText(QtGui.QApplication.translate("MainWindow", "Choose...", None, QtGui.QApplication.UnicodeUTF8))
        self.showLuminanceCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Show only luminance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Frame #2 compressed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Frame #2 reconstructed", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Motion vectors", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Block size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Search algorithm", None, QtGui.QApplication.UnicodeUTF8))
        self.searchTypeComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Full search", None, QtGui.QApplication.UnicodeUTF8))
        self.searchTypeComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Q-Step search", None, QtGui.QApplication.UnicodeUTF8))
        self.searchWindowSizeLabel.setText(QtGui.QApplication.translate("MainWindow", "Search window size", None, QtGui.QApplication.UnicodeUTF8))
        self.searchStepLabel.setText(QtGui.QApplication.translate("MainWindow", "Step", None, QtGui.QApplication.UnicodeUTF8))
        self.findVectorsPushButton.setText(QtGui.QApplication.translate("MainWindow", "Find vectors", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Frame reconstruction", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "MAD Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.reconstructFrame2PushButton.setText(QtGui.QApplication.translate("MainWindow", "Reconstruct  frame #2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "% of zero vectors:", None, QtGui.QApplication.UnicodeUTF8))
        self.zeroVectorsPercentLabel.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "% of motion vectors:", None, QtGui.QApplication.UnicodeUTF8))
        self.movedVectorsPercentLabel.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "% of new blocks:", None, QtGui.QApplication.UnicodeUTF8))
        self.newBlocksPercentLabel.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Compresssion ratio:", None, QtGui.QApplication.UnicodeUTF8))
        self.compressionRatioLabel.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Search time elapsed:", None, QtGui.QApplication.UnicodeUTF8))
        self.searchElapsedTimeLabel.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))

